-- 1. Tabel Produk (Jika belum ada atau ingin update)
-- Nonaktifkan RLS agar dapat diakses public (Anon)
CREATE TABLE IF NOT EXISTS produk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_barang TEXT NOT NULL,
    stok INTEGER DEFAULT 0,
    harga BIGINT DEFAULT 0,
    barcode TEXT UNIQUE,
    kategori TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Nonaktifkan RLS
ALTER TABLE produk DISABLE ROW LEVEL SECURITY;

-- 2. Tabel Transaksi (Header)
CREATE TABLE IF NOT EXISTS transaksi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no_struk TEXT UNIQUE NOT NULL,
    nama_pesanan TEXT, -- Untuk label pesanan yang disimpan (misal: "Meja 1")
    total_harga BIGINT DEFAULT 0,
    bayar BIGINT DEFAULT 0,
    kembali BIGINT DEFAULT 0,
    status TEXT DEFAULT 'completed', -- 'pending' (draft/simpan) atau 'completed' (lunas)
    kasir_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE transaksi DISABLE ROW LEVEL SECURITY;

-- 3. Tabel Detail Transaksi (Item)
CREATE TABLE IF NOT EXISTS detail_transaksi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaksi_id BIGINT REFERENCES transaksi(id) ON DELETE CASCADE,
    produk_id BIGINT REFERENCES produk(id),
    jumlah INTEGER NOT NULL,
    harga_satuan BIGINT NOT NULL,
    subtotal BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE detail_transaksi DISABLE ROW LEVEL SECURITY;

-- Trigger untuk update stok otomatis saat transaksi (INSERT)
CREATE OR REPLACE FUNCTION update_stok_setelah_transaksi()
RETURNS TRIGGER AS $$
BEGIN
    -- Kurangi stok untuk setiap item yang masuk (baik pending maupun completed)
    UPDATE produk
    SET stok = stok - NEW.jumlah
    WHERE id = NEW.produk_id;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_stok
AFTER INSERT ON detail_transaksi
FOR EACH ROW
EXECUTE FUNCTION update_stok_setelah_transaksi();

-- Trigger untuk mengembalikan stok saat item dihapus (DELETE)
CREATE OR REPLACE FUNCTION kembalikan_stok_setelah_hapus_detail()
RETURNS TRIGGER AS $$
BEGIN
    -- Kembalikan stok saat item transaksi dihapus atau draft dibatalkan
    UPDATE produk
    SET stok = stok + OLD.jumlah
    WHERE id = OLD.produk_id;
    
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_hapus_stok
AFTER DELETE ON detail_transaksi
FOR EACH ROW
EXECUTE FUNCTION kembalikan_stok_setelah_hapus_detail();

-- Trigger untuk penyesuaian stok saat jumlah item diubah (UPDATE)
CREATE OR REPLACE FUNCTION update_stok_perubahan_detail()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.produk_id = NEW.produk_id THEN
        -- Jika produk sama, sesuaikan selisihnya
        UPDATE produk
        SET stok = stok + OLD.jumlah - NEW.jumlah
        WHERE id = NEW.produk_id;
    ELSE
        -- Jika produk diganti, kembalikan stok lama dan kurangi stok baru
        UPDATE produk SET stok = stok + OLD.jumlah WHERE id = OLD.produk_id;
        UPDATE produk SET stok = stok - NEW.jumlah WHERE id = NEW.produk_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_edit_stok
AFTER UPDATE ON detail_transaksi
FOR EACH ROW
EXECUTE FUNCTION update_stok_perubahan_detail();

-- Insert dummy data produk
INSERT INTO produk (nama_barang, stok, harga, barcode, kategori)
VALUES 
('Kopi Susu', 100, 15000, '888001', 'Minuman'),
('Roti Bakar', 50, 12000, '888002', 'Makanan'),
('Teh Manis', 200, 5000, '888003', 'Minuman')
ON CONFLICT DO NOTHING;

-- 4. Tabel Kategori Produk
CREATE TABLE IF NOT EXISTS kategori_produk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE kategori_produk DISABLE ROW LEVEL SECURITY;

INSERT INTO kategori_produk (nama) VALUES 
('Makanan'), 
('Minuman'), 
('Snack') 
ON CONFLICT DO NOTHING;
